Allow deletion of bot messages by reacting with :wastebasket:
SquidDev-CC/FAQBot-CC pull request #35
Opened 2021-08-17 21:34 UTC by SkyTheCodeMaster

This adds an `on_raw_reaction_add` event that:
* Checks if the message author is the the bot
* Checks if the reacted emote is a wastebasket
If both of those conditions are true, it calls `await message.delete()` on the message, leading to it's deletion.
This is a good change because it will allow people to delete the output of things like `%eval` without requiring staff assistance, which will declutter chats like #computercraft.

2021-08-17 21:36 UTC, SkyTheCodeMaster commented
If someone wants this limited to *only* `%eval` output, you could add `if message.attachments:` to the check for deletion. Empty lists (no attachments) are falsey in Python, so it would not let the message be deleted.

2021-08-17 22:04 UTC, Wojbie commented
It probably should only be limited to only if orginal %eval caller or moderator reacts with 🗑️

2021-08-17 22:43 UTC, SkyTheCodeMaster commented
The bot replies to the original message, so it *should* be possible to have it only be with the original caller, check something like `payload.user == message.reference.resolved.author`? Then also do a check if a person reacting has a role named "Moderator", or a specific permission, like `Manage Messages`?

2021-08-18 08:47 UTC, SquidDev requested changes
Thank you for putting this together!

I think let's keep it simple for now and just have the original caller. Moderators can delete messages the old-fashioned way, and voting is probably a little too much.

`payload.user == message.reference.resolved.author` seems reasonable (though probably needs a check for `message.reference` and `message.reference.resolved` being `None`).

2021-08-18 08:47 UTC, SquidDev commented on ccfaq/__init__.py
> +async def on_raw_reaction_add(payload):
I think it's worth doing `on_reaction_add` here instead. This does mean it only works on the last 1k messages, but that's acceptable given you only really want to use it on recent messages.

This means we can drop the `fetch_channel`/`fetch_message` calls, which are expensive to do for every single reaction.

Alternatively, we should at least move the `str(payload.emoji) == "\U0001f5d1\U0000fe0f"` to the top of this function, so we're only making those requests on relevant messages.

2021-08-18 19:00 UTC, SkyTheCodeMaster commented
The reason I originally had it as `on_raw_reaction_add` is because when programming my own bot, I found that without the `raw` event, it only retrieved reactions on messages that were sent *after* the bot started, whereas the `raw` event received reactions from messages before the bot started.

2021-08-19 18:00 UTC, merged