Update center_write.md
SquidDev-CC/FAQBot-CC pull request #45
Opened 2022-11-30 11:35 UTC by macks2008

rephrased and elaborated the explanation of the suggested code. Also a slight refactor to extract the new X value (to make it easier to describe the steps). I don't THINK I broke the example, but I also didn't test it to be sure.

This all started because I noticed the apostrophe after the word "object" was playing hide and seek with you. Funny how that happens sometimes...

2022-12-02 22:08 UTC, SquidDev requested changes

2022-12-02 22:08 UTC, SquidDev commented on faqs/center_write.md
> +Finally, it sets the text cursor  to this x position, and the cursor's current y position.
```suggestion
Finally, it moves the cursor to this x position and the current y position.
```

2022-12-02 22:08 UTC, SquidDev commented on faqs/center_write.md
> +    term.setCursorPos(newX, y)
```suggestion
    local new_x = math.ceil((width / 2) - (text:len() / 2))
    term.setCursorPos(new_y, y)
```

2022-12-02 22:09 UTC, merged

2022-12-02 22:09 UTC, SquidDev commented
The phrasing of the whole FAQ is pretty clunky, but this is a definite improvement. Thank you!

2022-12-03 05:08 UTC, Wojbie commented on faqs/center_write.md
> +    term.setCursorPos(new_y, y)
Typo